kt_project/kt_project/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.shortcuts import render
from django.conf.urls.static import static
from django.conf import settings

app_name = 'main'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.test, name='main'),
    path('user/', include('userinformation.urls')),
    path('qna/', include('qna.urls')),
    path('pillinfo/', include('pillinfo.urls')),
    path('prescription/', include('prescription.urls')),
    path('userpill/', include('userpill.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

kt_project/pillinfo/urls.py
from django.urls import path, include
from django.shortcuts import render

from . import views



app_name = 'pillinfo'
urlpatterns = [
    path('', views.pillinfo_main, name='pillinfo_main'),
    path('pillinfo/', views.pillinfo, name='pillinfo'),
    path('prescription_upload/', views.prescription_upload, name='prescription_upload'),
    path('pill_upload/', views.upload_image, name='pill_upload'),
    path('api/pill_upload/', views.PillUploadView.as_view(), name='api-pill-upload'),
    path('api/pill_name_upload/', views.PillUploadNameView.as_view(), name='api-pill-name-upload'),
    path('api/PillInfoView/', views.PillInfoView.as_view(), name='api-Pill-InfoView'),
    path('api/PillInfoView_inter/', views.PillInfoView_inter.as_view(), name='api-Pill-InfoView-inter'),
    path('api/PillInfoView_inter_full/', views.PillInfoView_inter_full.as_view(), name='api-Pill-InfoView-inter-full'),
]

kt_project/qna/urls.py
from django.urls import path, include
from . import views
from django.shortcuts import render


app_name = 'qna'
urlpatterns = [
    path('', views.qna_home, name='home'),
    path('qna_list/', views.qna_list, name='qna_list'),
    path('qna_create/',  views.QnaCreate.as_view(), name='qna_create'),
    path('qna_detail/', views.qna_detail, name='qna_detail'),
    # path('qna_update/', views.qna_update, name='qna_update'),
    # path('qna_answer_update/', views.QnaUpdate.as_view(), name='qna_answer_update'),
    path('qna_answer_update/<int:pk>/', views.QnaUpdate.as_view(), name='qna_answer_update'),
    path('qna_delete/<int:pk>/', views.qna_delete, name='qna_delete'),
    # path('qna_user_detail/', views.qna_user_detail, name='qna_user_detail'),
]

kt_project/pillinfo/models.py
# from django.db import models

# # Create your models here.

# from django.db import models


# class Pill_Info(models.Model):
#     제품명A = models.CharField(max_length=50)
#     품목일련번호 = models.CharField(max_length=50)
#     주성분 = models.CharField(max_length=50)
#     효능 = models.CharField(max_length=50)
#     사용법 = models.CharField(max_length=50)
#     사전지식 = models.CharField(max_length=50)
#     주의음식= models.CharField(max_length=50)
#     이상반응 = models.CharField(max_length=50)
#     보관법 = models.CharField(max_length=50)
#     사업자번호 = models.CharField(max_length=50)

#     def __str__(self):
#         return self.제품명A

kt_project/pillinfo/views.py
from django.shortcuts import render
from rest_framework.parsers import MultiPartParser, FormParser
from rest_framework.response import Response
from rest_framework.views import APIView
from rest_framework import status
from rest_framework.parsers import JSONParser
from . import models
import requests
import json
import xmltodict
from urllib.parse import quote
from django.core.files.storage import FileSystemStorage
from ultralytics import YOLO
from PIL import Image
import logging
import os
import tempfile
import base64
from io import BytesIO
import io

from detect_pill_info.models import e_pill_info
from pill_img_info.models import pill_img_info

from userinformation.models import AccountInfo
from userpill.models import user_pill
from pill_img_info.models import pill_img_info
from detect_pill_info.models import e_pill_info

NUM_OF_ROWS = 100

logging.basicConfig(level=logging.INFO)
model = YOLO('../detect_model/best_0.994.pt')# 본인이 가지고 있는 모델 위치 (클라우드 서비스시 변경)

API_KEY = "6%2FBZRxNWs8dwSWMBNFk4YXzxB8tAKqONGDN9Qfqo9AJObQTkju5Efo%2B3P7uj08K59XXfVCGm7sn9iWWDklkHtw%3D%3D" # api key와 endpoint

base_url = "http://apis.data.go.kr/1471000/DURPrdlstInfoService02"
endpoint_interaction = "/getUsjntTabooInfoList02"
endpoint_age_restriction = "/getSpcifyAgrdeTabooInfoList2"
endpoint_pregnancy_restriction = "/getPwnmTabooInfoList2"
endpoint_elderly_caution = "/getOdsnAtentInfoList2"


def decode_base64_image(data):
    if 'data:' in data and ';base64,' in data:
        header, data = data.split(';base64,')

    decoded_data = base64.b64decode(data)
    image = BytesIO(decoded_data)

    image = Image.open(image)

    return image

def return_pill_name(image):
    fs = FileSystemStorage()
    filename = fs.save(image.name, image)
    file_path = fs.path(filename)
    results = model(file_path)
    cls_results = results[0].boxes.cls.tolist()
    pills = [results.names[int(index)] for index in cls_results]
    return pills



def get_pill_info(item_name):
    encoded_item_name = quote(item_name)
    url = f"{base_url}{endpoint_interaction}?serviceKey={API_KEY}&numOFRows={NUM_OF_ROWS}&itemName={encoded_item_name}"
    try:
        response = requests.get(url, verify=False)
        response_dict = xmltodict.parse(response.text)

        if 'response' in response_dict and 'body' in response_dict['response'] and 'items' in response_dict['response']['body']:
            items = response_dict['response']['body']['items']['item']
            pill_info = []

            if isinstance(items, list):
                for item in items:
                    info = {
                        'TYPE_NAME': item['TYPE_NAME'],
                        'ITEM_NAME': item['ITEM_NAME'],
                        'MIXTURE_INGR_KOR_NAME': item['MIXTURE_INGR_KOR_NAME'],
                        'INGR_ENG_NAME': item['INGR_ENG_NAME'],
                        'MIXTURE_ITEM_NAME': item['MIXTURE_ITEM_NAME'],
                        'INGR_CODE': item['INGR_CODE'],
                        'PROHBT_CONTENT': item['PROHBT_CONTENT'],
                        'ENTP_NAME': item['ENTP_NAME'],
                    }
                    pill_info.append(info)
            else:
                item = items
                info = {
                    'TYPE_NAME': item['TYPE_NAME'],
                    'ITEM_NAME': item['ITEM_NAME'],
                    'MIXTURE_INGR_KOR_NAME': item['MIXTURE_INGR_KOR_NAME'],
                    'INGR_ENG_NAME': item['INGR_ENG_NAME'],
                    'MIXTURE_ITEM_NAME': item['MIXTURE_ITEM_NAME'],
                    'INGR_CODE': item['INGR_CODE'],
                    'PROHBT_CONTENT': item['PROHBT_CONTENT'],
                    'ENTP_NAME': item['ENTP_NAME'],
                }

                pill_info.append(info)
            return pill_info

    except Exception as e:
        print(f"API 통신 중 에러 발생: {e}")

    return []  # 데이터가 없거나 API 통신 중 예외가 발생한 경우 빈 리스트 반환

def pillinfo(pill_names):

    pill_info_list = []
    
    for pill_name in pill_names:
        pill_info = e_pill_info.objects.filter(제품명A__contains=pill_name)

        if not pill_info:
            pill_info_list.append({})
            continue

        for pill in pill_info:
            pill_info_list.append({
                '제품명A': pill.제품명A,
                '품목일련번호': pill.품목일련번호,
                '주성분': pill.주성분,
                '효능': pill.효능,
                '사용법': pill.사용법,
                '사전지식': pill.사전지식,
                '주의음식': pill.주의음식,
                '이상반응': pill.이상반응,
                '보관법': pill.보관법,
                '사업자번호': pill.사업자번호,
                'url_key': pill.url_key
            })
            
    return pill_info_list

def get_pill_img_info(pill_names):

    pill_img_info_list = []
    
    for pill_name in pill_names:
        pill_info = pill_img_info.objects.filter(dl_name__contains=pill_name)

        if not pill_info:
            pill_img_info_list.append({})
            continue

        for pill_img in pill_info:
            pill_img_info_list.append({
                'item_seq': pill_img.item_seq,
                'dl_name': pill_img.dl_name,
                'img_key': pill_img.img_key,
                'drug_shape': pill_img.drug_shape,
                'print_front': pill_img.print_front,
                'print_back': pill_img.print_back,
                'color_class1': pill_img.color_class1,
                'color_class2': pill_img.color_class2,
            })
            
    return pill_img_info_list


def pillinfo_main(req):
    return render(req, 'pillinfo/pillinfo_main.html')

def prescription_upload(req):
    return render(req, 'pillinfo/prescription_upload.html')


def pill_upload(req):
    return render(req, 'pillinfo/pill_upload.html')

def string_to_ASCII(item):
    return quote(item)

def get_restriction_info(url, item_key):
    response = requests.get(url)
    response_dict = xmltodict.parse(response.text)

    if response_dict['response']['header']['resultCode'] != '00':
        print(f"Error: {response_dict['response']['header']['resultMsg']}")
        return []

    items = response_dict['response']['body'].get('items')

    if not items:
        return []

    items = items['item']

    return [(item.get(item_key), item.get('PROHBT_CONTENT')) for item in items] if isinstance(items, list) else [
        (items.get(item_key), items.get('PROHBT_CONTENT'))]

def check_interaction_info(item_name):
    url = f"{base_url}{endpoint_interaction}?serviceKey={API_KEY}&numOFRows={NUM_OF_ROWS}&itemName={string_to_ASCII(item_name)}"
    return get_restriction_info(url, 'MIXTURE_ITEM_NAME')

def get_age_restriction_info(item_name):
    url = f"{base_url}{endpoint_age_restriction}?serviceKey={API_KEY}&numOFRows={NUM_OF_ROWS}&itemName={string_to_ASCII(item_name)}"
    return get_restriction_info(url, 'ITEM_NAME')

def get_pregnancy_restriction_info(item_name):
    url = f"{base_url}{endpoint_pregnancy_restriction}?serviceKey={API_KEY}&numOFRows={NUM_OF_ROWS}&itemName={string_to_ASCII(item_name)}"
    return get_restriction_info(url, 'ITEM_NAME')

def get_elderly_caution_info(item_name):
    url = f"{base_url}{endpoint_elderly_caution}?serviceKey={API_KEY}&numOFRows={NUM_OF_ROWS}&itemName={string_to_ASCII(item_name)}"
    return get_restriction_info(url, 'ITEM_NAME')

def check_medication(medication, is_pregnant, user_num):
    is_safe_to_take = True
    restriction_issues = []  # 문제가 있는 약물과 이유를 저장할 리스트 생성

    is_elderly = 23 <= int(user_num[:2]) < 60
    is_specific_age = 10 < int(user_num[:2]) <= 23

    if is_pregnant == 'Y':
        logs = get_pregnancy_restriction_info(medication)
        if logs:
            for log in logs:
                restriction_issues.append({'medication': log[0], 'reason': log[1], 'type': '임부금기'})
            is_safe_to_take = False

    if is_elderly:
        logs = get_elderly_caution_info(medication)
        if logs:
            for log in logs:
                restriction_issues.append({'medication': log[0], 'reason': log[1], 'type': '노인주의'})
            is_safe_to_take = False

    if is_specific_age:
        logs = get_age_restriction_info(medication)
        if logs:
            for log in logs:
                restriction_issues.append({'medication': log[0], 'reason': log[1], 'type': '특정 연령주의'})
            is_safe_to_take = False

    return is_safe_to_take, restriction_issues  # 문제 여부와 문제 정보를 모두 반환


def upload_image(request):
    context = {}
    current_medication = []

    if request.method == 'POST':
        if 'pill_image' not in request.FILES:
            # context에 error message 추가하고 template을 반환
            context['error_message'] = '알약 이미지를 선택해주세요.'
            return render(request, 'pillinfo/pill_upload.html', context)

        uploaded_file = request.FILES['pill_image']

        # 임시 파일 생성
        with tempfile.NamedTemporaryFile(delete=False) as temp_file:
            temp_file.write(uploaded_file.read())
            temp_file_path = temp_file.name
        results = model(temp_file_path)
        cls_indices = results[0].boxes.cls.tolist()
        detected_names = [results[0].names[int(index)] for index in cls_indices]
        temp_current_medication = []
        interaction_issues = []

        for pill in detected_names:
            temp_current_medication.append(pill)

        for medication in temp_current_medication + sum(current_medication, []):
            logs = check_interaction_info(medication)

            for log in logs:
                if log[0] in temp_current_medication + sum(current_medication, []):
                    issue = {
                        'medication': log[0],
                        'reason': log[1],
                        'current_medication': medication
                    }
                    interaction_issues.append(issue)

        if interaction_issues:
            context['interaction_issues'] = interaction_issues

        is_safe_to_take, restriction_issues = check_medication(
            temp_current_medication
        )

kt_project/pillinfo/templates/pillinfo/pill_upload.html
<h1>알약 사진 업로드</h1>

<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="file" name="pill_image">
    <button type="submit">업로드</button>
</form>

{% if error_message %}
    <p class="error">{{ error_message }}</p>
{% endif %}

{% if results %}
    <h2>Detected Pills:</h2>
    <ul>
    {% for name in results %}
        <li>{{ name }}</li>
    {% endfor %}
    </ul>
{% endif %}

<<<<<<< HEAD
<<<<<<< HEAD
=======
>>>>>>> main
{% if interaction_issues %}
    <h2>Interaction Issues:</h2>
    <ul>
    {% for issue in interaction_issues %}
        <li>
            <p>Medication: {{ issue.medication }}</p>
            <p>Current Medication: {{ issue.current_medication }}</p>
            <p>Reason: {{ issue.reason }}</p>
        </li>
    {% endfor %}
    </ul>
{% endif %}
<<<<<<< HEAD
=======

>>>>>>> e8b626112dba1cce044e3e215f7e2c0949c59d52
=======
>>>>>>> main

{% if restriction_issues %}
    <h2>Restriction Issues:</h2>
    <ul>
    {% for issue in restriction_issues %}
        <li>
            <h3>Type: {{ issue.type }}</h3>  <!-- 문제 유형 출력 -->
            <p>Medication: {{ issue.medication }}</p>  <!-- 문제가 되는 약물 출력 -->
            <p>Reason: {{ issue.reason }}</p>  <!-- 문제 이유 출력 -->
        </li>
    {% endfor %}
    </ul>
{% endif %}

kt_project/pillinfo/templates/pillinfo/pillinfo.html
<h1>알약 정보</h1>

<form method="POST">
    {% csrf_token %}
    <input type="text" name="pill_name" placeholder="알약 이름을 입력하세요">
    <button type="submit">검색</button>
</form>

<h2>알약 정보 리스트:</h2>
{% if pill_info_list %}
    <ul>
        {% for pill_info in pill_info_list %}
            <li><strong>판별한 제품명:</strong> {{ pill_info.제품명A }}</li>
            <li><strong>제품의 주성분:</strong> {{ pill_info.주성분 }}</li>
            <li><strong>제품의 효능:</strong> {{ pill_info.효능 }}</li>
            <li><strong>제품 사용법:</strong> {{ pill_info.사용법 }}</li>
            <li><strong>제품 사용전 알아둬야할 점:</strong> {{ pill_info.사전지식 }}</li>
            <li><strong>제품과 함께 먹을 때 주의해야할 음식:</strong> {{ pill_info.주의음식 }}</li>
            <li><strong>제품의 부작용:</strong> {{ pill_info.이상반응 }}</li>
            <li><strong>제품 보관방법:</strong> {{ pill_info.보관법 }}</li>
            <hr>
        {% endfor %}
    </ul>
{% else %}
    <p>검색 결과가 없습니다.</p>
{% endif %}

<hr>

<h2>복용 금지 약물 리스트</h2>
{% if api_pill_info_list %}
    <ul>
        {% for poc_info in api_pill_info_list %}
            <li><strong>제품명A:</strong> {{ poc_info.ITEM_NAME }}</li>
            <li><strong>제품명B:</strong> {{ poc_info.MIXTURE_ITEM_NAME }}</li>
            <li><strong>성분명B:</strong> {{ poc_info.INGR_ENG_NAME }}</li>
            <li><strong>같이 섭취 시 부작용:</strong> {{ poc_info.PROHBT_CONTENT }}</li>
            <hr>
        {% endfor %}
    </ul>
{% else %}
    <p>해당 알약에 대한 복용 금지 약물 정보가 없습니다.</p>
{% endif %}

kt_project/pillinfo/templates/pillinfo/pillinfo_main.html
<h1>선택</h1>

<form method="POST">
    {% csrf_token %}
    <a href="{% url 'pillinfo:prescription_upload' %}">
        <button type="button">처방전 사진 찍기</button>
    </a>
    <a href="{% url 'pillinfo:pill_upload' %}">
        <button type="button">알약 사진 찍기</button>
    </a>
    <a href="{% url 'pillinfo:pillinfo' %}">
        <button type="button">알약 이름 검색</button>
    </a>
</form>

kt_project/pillinfo/templates/pillinfo/prescription_upload.html
<h1>처방전 사진 업로드</h1>

<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="file" name="prescription_image">
    <button type="submit">업로드</button>
</form>